blank_issues_enabled: false
contact_links:
  - name: Smart Autotune Thermostat Community Forum
    url: https://github.com/Alexwijn/SAT/discussions
    about: Ask questions or discuss the integration here.
